export const KIT_CONTRACT_VERSION = "0.1.0";

export const KIT_CONTRACT_FIELDS = Object.freeze([
  "domainPath",
  "purpose",
  "publicApi",
  "internalApi",
  "events",
  "snapshot",
  "reset",
  "dataExposed",
  "validator",
  "graduationRule",
]);

const defaultGraduationRule = "Promotable when the API is neutral, deterministic, documented, resettable, snapshot-safe, and validated outside one game.";
const defaultReset = "Clear runtime-local buffers and rebuild deterministic state from public API input plus minimal config.";

function createGenericContract(input) {
  return Object.freeze({
    layer: "generic-incubator",
    version: KIT_CONTRACT_VERSION,
    graduationStatus: "local-incubation",
    reset: defaultReset,
    graduationRule: defaultGraduationRule,
    ...input,
  });
}

function createGoldRushContract(input) {
  return Object.freeze({
    layer: "goldrush-custom",
    version: KIT_CONTRACT_VERSION,
    graduationStatus: "game-specific",
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
    reset: input.reset ?? "Reset game-specific state through the owning GoldRush runtime phase or match restart.",
    graduationRule: "Not promotable as-is because it owns GoldRush naming, rules, tuning, content, or presentation.",
    ...input,
  });
}

export const genericIncubatorKitContracts = Object.freeze([
  createGenericContract({
    domainPath: "n:runtime:domain-registry",
    apiName: "runtimeDomainRegistry",
    purpose: "Index installed domain service kits and expose dependency health.",
    publicApi: ["contract", "snapshot", "validate"],
    internalApi: ["indexInstalledKits", "buildDependencyGraph", "assertContractShape"],
    events: ["kit.registered", "kit.healthChanged"],
    snapshot: ["registeredKits", "dependencyGraph", "health"],
    dataExposed: ["kit ids", "domain paths", "requires/provides graph", "health state"],
    validator: "tools/validation/validate-runtime-kit-registry.mjs",
  }),
  createGenericContract({
    domainPath: "n:runtime:events",
    apiName: "runtimeEvents",
    purpose: "Provide a small event stream contract for kit-to-kit facts.",
    publicApi: ["emit", "events", "clear", "validate"],
    internalApi: ["dedupeEvent", "trimEventLog", "normalizePayload"],
    events: ["event.emitted", "event.rejected"],
    snapshot: ["recentEvents", "eventCount", "lastEvent"],
    dataExposed: ["event id", "event type", "tick", "payload summary"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:runtime:snapshot",
    apiName: "runtimeSnapshot",
    purpose: "Create serializable state envelopes for debug, sync, replay, and validation.",
    publicApi: ["capture", "latest", "validate"],
    internalApi: ["cloneSerializable", "redactInternalFields", "stampSnapshot"],
    events: ["snapshot.captured"],
    snapshot: ["snapshotId", "version", "state", "metadata"],
    dataExposed: ["state envelope", "metadata", "capture reason"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:runtime:validation",
    apiName: "runtimeValidation",
    purpose: "Aggregate validator results without making product claims.",
    publicApi: ["record", "snapshot", "validate"],
    internalApi: ["normalizeResult", "groupFailures", "resolveSeverity"],
    events: ["validation.recorded", "validation.failed"],
    snapshot: ["checks", "failures", "lastRun"],
    dataExposed: ["validator id", "status", "failures", "evidence path"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:scene:site-loader",
    apiName: "sceneSiteLoader",
    purpose: "Load scene-specific kit groups and expose activation receipts.",
    publicApi: ["activate", "snapshot", "validate"],
    internalApi: ["resolveSite", "loadKitGroup", "deactivatePrevious"],
    events: ["site.activated", "kitGroup.loaded", "kitGroup.deactivated"],
    snapshot: ["activeSite", "activeKitGroups", "loadedModules", "activationReceipts"],
    dataExposed: ["site id", "kit groups", "loaded modules", "activation receipt"],
    validator: "tools/validation/validate-scene-site-loader.mjs",
  }),
  createGenericContract({
    domainPath: "n:scene:transition",
    apiName: "sceneTransition",
    purpose: "Represent scene handoffs with deterministic transition receipts.",
    publicApi: ["transition", "phase", "snapshot"],
    internalApi: ["resolveTransition", "recordHistory", "applyCueState"],
    events: ["scene.transitionStarted", "scene.transitionCompleted"],
    snapshot: ["currentSceneId", "lastTransition", "history"],
    dataExposed: ["from scene", "to scene", "audio cue", "animation cue", "reason"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:network:party-room",
    apiName: "networkPartyRoom",
    purpose: "Own small party rooms, leader state, join codes, and ready receipts.",
    publicApi: ["create", "join", "leave", "start", "snapshot"],
    internalApi: ["allocateCode", "broadcastState", "enforceCapacity"],
    events: ["party.created", "party.joined", "party.left", "party.started", "party.rosterReduced"],
    snapshot: ["code", "leaderId", "members", "readyState", "disconnectPolicy"],
    dataExposed: ["party code", "leader", "member count", "launch receipt", "disconnect policy"],
    validator: "tools/validation/validate-network-kit.mjs",
  }),
  createGenericContract({
    domainPath: "n:network:room-partitions",
    apiName: "networkRoomPartitions",
    purpose: "Split large sessions into deterministic internal room partitions.",
    publicApi: ["generate", "joinPlayer", "leavePlayer", "handoff", "snapshot"],
    internalApi: ["compactRoster", "retainHighWaterPartition", "writeLedger"],
    events: ["partition.created", "player.joined", "player.left", "handoff.requested"],
    snapshot: ["partitions", "assignments", "ledger", "policy"],
    dataExposed: ["partition id", "capacity", "player count", "ledger writes"],
    validator: "tools/validation/validate-room-orchestration.mjs",
  }),
  createGenericContract({
    domainPath: "n:world:terrain-heightfield",
    apiName: "worldTerrainHeightfield",
    purpose: "Sample a deterministic terrain heightfield shared by rendering and movement.",
    publicApi: ["heightAt", "colorAt", "snapshot", "validate"],
    internalApi: ["sampleBands", "sampleRidges", "applyClearanceMasks"],
    events: ["terrain.sampled", "terrain.rebuilt"],
    snapshot: ["width", "depth", "sampleStep", "heightRules"],
    dataExposed: ["height", "color", "normal estimate", "band id"],
    validator: "tools/validation/validate-terrain-heightfield.mjs",
  }),
  createGenericContract({
    domainPath: "n:world:terrain-raycast",
    apiName: "worldTerrainRaycast",
    purpose: "Raycast down to visible terrain for placement and player grounding.",
    publicApi: ["raycastDown", "sampleGround", "validate"],
    internalApi: ["intersectTriangle", "barycentric2D", "selectNearBand"],
    events: ["terrain.raycastHit", "terrain.raycastMiss"],
    snapshot: ["lastHit", "raycastBounds", "bandPolicy"],
    dataExposed: ["hit point", "normal", "slope", "walkable state"],
    validator: "tools/validation/validate-terrain-raycast.mjs",
  }),
  createGenericContract({
    domainPath: "n:world:terrain-patches",
    apiName: "worldTerrainPatches",
    purpose: "Expose terrain patch windows and active patch ids for large worlds.",
    publicApi: ["snapshot", "windowForRoom", "patchForPoint", "validate"],
    internalApi: ["buildPatchGrid", "resolveActiveWindows", "clipPatchIds"],
    events: ["patchWindow.activated", "patchWindow.deactivated"],
    snapshot: ["patchGrid", "activePatchIds", "roomPatchWindows"],
    dataExposed: ["patch id", "room window", "origin patch", "patch radius"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:world:placement-raycast",
    apiName: "worldPlacementRaycast",
    purpose: "Place props and actors by querying terrain and avoidance rules.",
    publicApi: ["place", "batchPlace", "validate"],
    internalApi: ["resolveAnchor", "applyAvoidTags", "snapToTerrain"],
    events: ["placement.accepted", "placement.rejected"],
    snapshot: ["placements", "rejections", "rules"],
    dataExposed: ["object id", "anchor", "position", "ground height", "rejection reason"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:physics:world",
    apiName: "physicsWorld",
    purpose: "Own a physics step boundary and world-level physics metadata.",
    publicApi: ["step", "snapshot", "validate"],
    internalApi: ["syncBodies", "applyGravity", "resolveFixedStep"],
    events: ["physics.stepped", "physics.bodySynced"],
    snapshot: ["gravity", "stepSeconds", "bodyCount"],
    dataExposed: ["body ids", "gravity", "fixed step", "adapter metadata"],
    validator: "tools/validation/validate-physics-colliders.mjs",
  }),
  createGenericContract({
    domainPath: "n:physics:collider",
    apiName: "physicsCollider",
    purpose: "Build collider descriptors from shared terrain and world forms.",
    publicApi: ["build", "colliderFor", "snapshot", "validate"],
    internalApi: ["triangulateHeightfield", "registerBlocker", "syncAdapter"],
    events: ["collider.created", "collider.updated"],
    snapshot: ["colliders", "heightfield", "blockers"],
    dataExposed: ["collider id", "shape", "bounds", "blocking feature"],
    validator: "tools/validation/validate-physics-colliders.mjs",
  }),
  createGenericContract({
    domainPath: "n:physics:query",
    apiName: "physicsQuery",
    purpose: "Provide read-only physics queries for movement, aiming, and interaction.",
    publicApi: ["raycast", "sweep", "overlap", "validate"],
    internalApi: ["normalizeQuery", "filterCollisionLayers", "rankHits"],
    events: ["physics.queryHit", "physics.queryMiss"],
    snapshot: ["lastQueries", "queryPolicy"],
    dataExposed: ["hit object", "distance", "normal", "layer"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:control:third-person-camera",
    apiName: "controlThirdPersonCamera",
    purpose: "Resolve over-the-shoulder camera state from character pose and look input.",
    publicApi: ["setLook", "snapshot", "validate"],
    internalApi: ["clampPitch", "resolveShoulderOffset", "smoothFollow"],
    events: ["camera.lookChanged", "camera.modeChanged"],
    snapshot: ["yaw", "pitch", "target", "shoulderOffset", "mode"],
    dataExposed: ["camera position", "look target", "yaw", "pitch", "playability checks"],
    validator: "tools/validation/validate-third-person-controller.mjs",
  }),
  createGenericContract({
    domainPath: "n:control:character-movement",
    apiName: "controlCharacterMovement",
    purpose: "Move a character relative to camera look while respecting ground queries.",
    publicApi: ["applyInput", "teleport", "snapshot", "validate"],
    internalApi: ["resolveCameraRelativeVector", "sampleGround", "applyStepLimit"],
    events: ["character.moved", "character.grounded", "character.blocked"],
    snapshot: ["position", "velocity", "grounded", "heading"],
    dataExposed: ["input vector", "position", "ground sample", "blocked reason"],
    validator: "tools/validation/validate-third-person-controller.mjs",
  }),
  createGenericContract({
    domainPath: "n:render:three-scene",
    apiName: "renderThreeScene",
    purpose: "Own Three.js scene, camera, renderer lifecycle, and resize policy.",
    publicApi: ["mount", "render", "unmount", "snapshot"],
    internalApi: ["createRenderer", "syncCamera", "disposeResources"],
    events: ["render.mounted", "render.frame", "render.unmounted"],
    snapshot: ["mounted", "size", "sceneObjectCount", "rendererInfo"],
    dataExposed: ["renderer state", "camera state", "object count"],
    validator: "tools/validation/validate-render-instancing.mjs",
  }),
  createGenericContract({
    domainPath: "n:render:terrain-bands",
    apiName: "renderTerrainBands",
    purpose: "Render large terrain as banded tessellated mesh from one terrain algorithm.",
    publicApi: ["buildGeometry", "snapshot", "validate"],
    internalApi: ["pushTerrainCell", "windTopFaces", "buildSkirts"],
    events: ["terrainMesh.built"],
    snapshot: ["bands", "vertices", "triangles", "continuity"],
    dataExposed: ["band id", "vertex count", "triangle count", "continuity metadata"],
    validator: "tools/validation/validate-terrain-continuity.mjs",
  }),
  createGenericContract({
    domainPath: "n:render:micro-object-instancing",
    apiName: "renderMicroObjectInstancing",
    purpose: "Batch many object descriptors into readable instanced render groups.",
    publicApi: ["batch", "snapshot", "validate"],
    internalApi: ["groupByArchetype", "resolveMaterial", "applyPlacement"],
    events: ["microObjects.batched"],
    snapshot: ["families", "instanceCount", "visibleClusters"],
    dataExposed: ["archetype", "role", "environment space", "instance transform"],
    validator: "tools/validation/validate-render-instancing.mjs",
  }),
  createGenericContract({
    domainPath: "n:render:character-preview",
    apiName: "renderCharacterPreview",
    purpose: "Render an inspectable 3D character preview with direct pointer rotation.",
    publicApi: ["mount", "rotate", "snapshot", "unmount"],
    internalApi: ["buildRig", "bindPointerDrag", "syncPedestal"],
    events: ["characterPreview.rotated", "characterPreview.selected"],
    snapshot: ["rotation", "pose", "assetStatus"],
    dataExposed: ["rotation", "pose id", "rig source", "asset status"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:audio:cue-state",
    apiName: "audioCueState",
    purpose: "Represent music and one-shot cue state without owning product audio assets.",
    publicApi: ["setCue", "oneShot", "snapshot", "validate"],
    internalApi: ["dedupeOneShot", "resolveCrossfade", "clampVolume"],
    events: ["audio.cueChanged", "audio.oneShot"],
    snapshot: ["musicCueId", "oneShots", "crossfadeSeconds", "volume"],
    dataExposed: ["cue id", "loop state", "volume", "dedupe id"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:animation:state",
    apiName: "animationState",
    purpose: "Expose animation state descriptors from movement, interaction, and combat facts.",
    publicApi: ["setState", "snapshot", "validate"],
    internalApi: ["resolveClipSlot", "blendParams", "dedupeTransitions"],
    events: ["animation.stateChanged", "animation.clipRequested"],
    snapshot: ["clipSlotIds", "params", "actionState"],
    dataExposed: ["clip slot", "blend parameters", "action state"],
    validator: "tools/validation/validate-domain-kit-contracts.mjs",
  }),
  createGenericContract({
    domainPath: "n:gameplay:interaction-hold",
    apiName: "gameplayInteractionHold",
    purpose: "Track hold-to-complete interactions with cancel and completion receipts.",
    publicApi: ["start", "tick", "cancel", "snapshot"],
    internalApi: ["resolveTarget", "applyProgressDecay", "emitReceipt"],
    events: ["interaction.started", "interaction.progressed", "interaction.completed", "interaction.cancelled"],
    snapshot: ["targetId", "progress", "requiredSeconds", "lastReceipt"],
    dataExposed: ["target id", "progress", "required time", "receipt"],
    validator: "tools/validation/validate-gameplay-loop.mjs",
  }),
  createGenericContract({
    domainPath: "n:gameplay:cargo",
    apiName: "gameplayCargo",
    purpose: "Own carried resource capacity, drops, penalties, and transfer receipts.",
    publicApi: ["seed", "add", "drop", "snapshot"],
    internalApi: ["clampCapacity", "calculatePenalty", "recordTransfer"],
    events: ["cargo.added", "cargo.dropped", "cargo.capacityReached"],
    snapshot: ["carriedByEntity", "capacity", "dropReceipts"],
    dataExposed: ["entity id", "amount", "capacity", "weight penalty"],
    validator: "tools/validation/validate-gameplay-loop.mjs",
  }),
  createGenericContract({
    domainPath: "n:gameplay:extraction",
    apiName: "gameplayExtraction",
    purpose: "Validate extraction volumes, deposits, timers, and completion receipts.",
    publicApi: ["enter", "tick", "deposit", "snapshot"],
    internalApi: ["checkVolume", "preventDuplicateDeposit", "applyMultiplier"],
    events: ["extraction.entered", "extraction.completed", "extraction.rejected"],
    snapshot: ["sites", "activeSiteId", "progress", "receipts"],
    dataExposed: ["site id", "progress", "deposit amount", "receipt status"],
    validator: "tools/validation/validate-gameplay-loop.mjs",
  }),
  createGenericContract({
    domainPath: "n:gameplay:combat-pressure",
    apiName: "gameplayCombatPressure",
    purpose: "Represent pressure from threats, damage, and combat state changes.",
    publicApi: ["enter", "damage", "exit", "snapshot"],
    internalApi: ["activateThreats", "clampPressure", "recordDamage"],
    events: ["combat.entered", "combat.damageApplied", "combat.exited"],
    snapshot: ["active", "pressure", "threats", "receipts"],
    dataExposed: ["threat id", "pressure", "damage receipt", "active state"],
    validator: "tools/validation/validate-gameplay-loop.mjs",
  }),
  createGenericContract({
    domainPath: "n:match:lifecycle",
    apiName: "matchLifecycle",
    purpose: "Own deterministic match phase, clock, lifecycle status, and end requests.",
    publicApi: ["start", "advancePhase", "tick", "requestEnd", "snapshot"],
    internalApi: ["preventRegression", "recordPhaseHistory", "resolveEndCondition"],
    events: ["match.started", "match.phaseChanged", "match.ended"],
    snapshot: ["matchId", "phase", "tick", "elapsedSeconds", "status"],
    dataExposed: ["phase", "tick", "status", "phase history"],
    validator: "tools/validation/validate-match-lifecycle.mjs",
  }),
  createGenericContract({
    domainPath: "n:match:receipts",
    apiName: "matchReceipts",
    purpose: "Store accepted, rejected, duplicate, and handoff receipts for replay-safe systems.",
    publicApi: ["record", "receipt", "snapshot", "validate"],
    internalApi: ["dedupeReceipt", "indexByPlayer", "indexByTeam"],
    events: ["receipt.accepted", "receipt.rejected", "receipt.duplicate"],
    snapshot: ["receipts", "appliedIds", "rejectedIds", "totals"],
    dataExposed: ["receipt id", "status", "player id", "team id", "value"],
    validator: "tools/validation/validate-match-results.mjs",
  }),
  createGenericContract({
    domainPath: "n:match:scoring",
    apiName: "matchScoring",
    purpose: "Apply scoring rules to receipts and expose deterministic leaders.",
    publicApi: ["applyReceipt", "applyPenalty", "snapshot", "validate"],
    internalApi: ["resolveTeamScore", "sortLeaders", "applyModifiers"],
    events: ["score.applied", "score.penaltyApplied", "score.leaderChanged"],
    snapshot: ["players", "teams", "leaders", "modifiers"],
    dataExposed: ["player score", "team score", "modifier", "leader"],
    validator: "tools/validation/validate-match-results.mjs",
  }),
  createGenericContract({
    domainPath: "n:match:results",
    apiName: "matchResults",
    purpose: "Finalize match outcome, placements, awards, and replay digest references.",
    publicApi: ["finalize", "snapshot", "validate"],
    internalApi: ["rankPlacements", "resolveAwards", "freezeResults"],
    events: ["results.finalized"],
    snapshot: ["winner", "placements", "awards", "finalReason"],
    dataExposed: ["winner", "placement", "award", "final reason"],
    validator: "tools/validation/validate-match-results.mjs",
  }),
]);

export const goldRushKitContracts = Object.freeze([
  createGoldRushContract({
    domainPath: "n:goldrush:runtime",
    purpose: "Compose generic and GoldRush kits into the playable runtime facade.",
    publicApi: ["generateMatch", "mineGold", "cashOut", "takeDamage", "snapshot"],
    internalApi: ["tickEngine", "bridgeScenarioState", "advanceRuntimePhase"],
    events: ["goldrush.runtimeTicked", "goldrush.runtimeCommandAccepted"],
    snapshot: ["scenario", "network", "kitContracts", "installOrder"],
    dataExposed: ["runtime state", "installed kit graph", "current scenario"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:replay-summary",
    purpose: "Convert GoldRush event and receipt facts into a compact match replay summary.",
    publicApi: ["appendEvent", "capture", "snapshot", "validate"],
    internalApi: ["selectKeyMoments", "dedupeEvents", "summarizeReceipts"],
    events: ["goldrush.replayEventAdded", "goldrush.replayCaptured"],
    snapshot: ["keyMoments", "events", "resultSummary", "frontierConditionSummary", "extractionContestSummary"],
    dataExposed: ["event type", "tick", "payload", "result digest", "condition digest", "contest digest"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:match-snapshot",
    purpose: "Expose one GoldRush match snapshot for debug, sync, and UI.",
    publicApi: ["snapshot", "validate"],
    internalApi: ["collectEngineState", "redactInternalPartitions", "serializeScenario"],
    events: ["goldrush.snapshotCaptured"],
    snapshot: ["match", "world", "player", "cargo", "score"],
    dataExposed: ["match state", "world state", "player state", "cargo", "score"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:reality-status",
    purpose: "Prevent prototype, placeholder, and cloud-blocked domains from being mistaken for final parity.",
    publicApi: ["snapshot", "validate"],
    internalApi: ["resolveDomainState", "countPlaceholderSlots", "groupBlockedDomains"],
    events: ["goldrush.realityStatusChanged"],
    snapshot: ["domains", "summary", "requiredProof"],
    dataExposed: ["domain status", "current truth", "next action", "proof list"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:scene-flow",
    purpose: "Route title, lobby, loading yard, gold field, combat, extract, and results scenes.",
    publicApi: ["transition", "phase", "snapshot"],
    internalApi: ["transitionForPhase", "resolveAudioCue", "resolveAnimationCue"],
    events: ["goldrush.sceneChanged", "goldrush.phaseSceneResolved"],
    snapshot: ["currentSceneId", "activeAudioCueId", "activeAnimationCueId", "history"],
    dataExposed: ["scene id", "transition id", "cue ids", "reason"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:train-loading",
    purpose: "Own the GoldRush loading-yard train handoff into the large match.",
    publicApi: ["activate", "boardPartyMember", "depart", "snapshot"],
    internalApi: ["resolveBoardingZone", "createBoardingManifest", "resolvePeerHandoffGate", "reduceDisconnectedRoster", "createDepartureReceipt", "handoffToMatch"],
    events: ["goldrush.trainBoarded", "goldrush.partyMemberAutoBoarded", "goldrush.partyBoardingReady", "goldrush.peerHandoffGateReady", "goldrush.partyMemberDisconnected", "goldrush.trainDeparted"],
    snapshot: ["boardingManifest", "boardingStatus", "peerHandoffGate", "trainState", "handoffReceipt"],
    dataExposed: ["boarding player ids", "seat readiness", "peer readiness", "disconnect policy", "train phase", "handoff payload"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:party-lobby",
    purpose: "Own the four-player GoldRush party-code lobby before a leader starts the mass match.",
    publicApi: ["createCode", "joinCode", "leave", "startMatch", "reportBoardingStatus", "snapshot"],
    internalApi: ["syncPeerState", "enforceLeaderStart", "broadcastLaunch", "fanoutBoardingState", "reduceDisconnectedRoster"],
    events: ["goldrush.partyCreated", "goldrush.partyJoined", "goldrush.partyLeft", "goldrush.partyLaunchRequested", "goldrush.partyBoardingStatusChanged", "goldrush.partyMemberDisconnected"],
    snapshot: ["partyCode", "leaderId", "members", "launchPayload", "boardingSync", "disconnectPolicy"],
    dataExposed: ["party code", "member list", "leader", "match launch request", "boarding readiness", "disconnect receipts"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:room-orchestration",
    purpose: "Hide internal 50-player partitions behind the GoldRush network contract.",
    publicApi: ["generate", "joinPlayer", "leavePlayer", "handoff", "snapshot"],
    internalApi: ["createSession", "compactAssignments", "retainPartition"],
    events: ["goldrush.partitionCreated", "goldrush.playerJoined", "goldrush.handoffRequested"],
    snapshot: ["policy", "partitions", "rooms", "ledger"],
    dataExposed: ["players", "partition capacity", "room windows", "ledger writes"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:desert-terrain",
    purpose: "Apply GoldRush canyon, basin, trail, gold seam, and mountain terrain rules.",
    publicApi: ["heightAt", "colorAt", "snapshot", "validate"],
    internalApi: ["sampleCentralMountainHeight", "sampleCanyonBasin", "sampleTrailCut"],
    events: ["goldrush.terrainSampled"],
    snapshot: ["scale", "bands", "mountainForms", "clearanceMasks"],
    dataExposed: ["height", "color", "band", "walkaround mask"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-grounding",
    purpose: "Keep the local prospector grounded on visible GoldRush terrain.",
    publicApi: ["raycastDown", "sampleGround", "snapshot"],
    internalApi: ["sampleTerrainCollider", "cacheRenderGround", "applyStepLimit"],
    events: ["goldrush.playerGrounded", "goldrush.playerBlocked"],
    snapshot: ["ground", "renderGround", "slope", "blockingFeatureId"],
    dataExposed: ["ground height", "slope", "walkable", "blocking feature"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:terrain-patch-windows",
    purpose: "Map GoldRush room windows to active terrain patch windows.",
    publicApi: ["snapshot", "windowForShard", "patchForPoint", "validate"],
    internalApi: ["resolveActiveWindows", "buildPatchGrid", "mapShardToWindow"],
    events: ["goldrush.patchWindowActivated"],
    snapshot: ["patchGrid", "roomPatchWindows", "activePatchIds"],
    dataExposed: ["patch id", "room window", "shard id", "active state"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:prop-placement",
    purpose: "Place GoldRush rocks, plants, props, towns, rails, mines, and gold markers by terrain raycast.",
    publicApi: ["place", "batchPlace", "snapshot"],
    internalApi: ["resolveEnvironmentSpace", "avoidRoutes", "snapToTerrain"],
    events: ["goldrush.propPlaced", "goldrush.propRejected"],
    snapshot: ["placements", "environmentSpaces", "microKitCounts"],
    dataExposed: ["object kit id", "environment space", "position", "ground height"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:frontier-conditions",
    purpose: "Expose GoldRush match conditions that change route planning, visibility, audio, lighting, risk, and gold pressure.",
    publicApi: ["generate", "setCondition", "advance", "snapshot", "effects", "reset", "validate"],
    internalApi: ["createConditionRotation", "weightedHash", "validateGoldRushFrontierConditionState"],
    events: ["goldrush.frontierConditionGenerated", "goldrush.frontierConditionChanged"],
    snapshot: ["active", "upcoming", "rotation", "modifiers", "world", "audio", "lighting", "effects"],
    dataExposed: ["condition id", "planning modifiers", "world descriptor", "audio descriptor", "lighting descriptor", "resolved effects"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:terrain-physics",
    purpose: "Bridge GoldRush terrain collider metadata into the selected physics adapter.",
    publicApi: ["step", "snapshot", "validate"],
    internalApi: ["createCannonHeightfield", "syncTerrainBodies", "resolvePhysicsGround"],
    events: ["goldrush.physicsStepped", "goldrush.terrainBodySynced"],
    snapshot: ["adapter", "heightfield", "bodyCount"],
    dataExposed: ["adapter name", "heightfield metadata", "body count"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:mountain-blockers",
    purpose: "Represent the central mountain and canyon blockers as GoldRush traversal constraints.",
    publicApi: ["colliderFor", "snapshot", "validate"],
    internalApi: ["sampleCentralMountainBlocker", "applyClearanceCorridors", "syncVisualFootprint"],
    events: ["goldrush.blockerCreated", "goldrush.blockerCleared"],
    snapshot: ["blockers", "clearanceCorridors", "visualFootprints"],
    dataExposed: ["blocker id", "radius", "route role", "clearance mask"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:ground-probes",
    purpose: "Expose GoldRush-specific ground, slope, walkability, and blocker probes.",
    publicApi: ["probe", "batchProbe", "snapshot"],
    internalApi: ["sampleTerrainCollider", "classifySlope", "rankGroundHits"],
    events: ["goldrush.groundProbeHit", "goldrush.groundProbeBlocked"],
    snapshot: ["lastProbe", "probePolicy", "failures"],
    dataExposed: ["position", "ground height", "walkable", "blocking feature"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:exploration-camera",
    purpose: "Drive the GoldRush over-the-shoulder exploration camera from mouse look and player pose.",
    publicApi: ["setMode", "snapshot", "validate"],
    internalApi: ["selectPerspectivePose", "resolveShoulderTarget", "applyMouseLook"],
    events: ["goldrush.cameraModeChanged", "goldrush.cameraPoseSelected"],
    snapshot: ["mode", "selectedPerspective", "threeDescriptor"],
    dataExposed: ["camera mode", "pose id", "position", "lookAt"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:prospector-movement",
    purpose: "Move the GoldRush prospector with WASD relative to the over-the-shoulder camera.",
    publicApi: ["applyInput", "teleport", "snapshot"],
    internalApi: ["resolveCameraYawMovement", "sampleGround", "animateLegs"],
    events: ["goldrush.prospectorMoved", "goldrush.prospectorGrounded"],
    snapshot: ["position", "velocity", "look", "ground"],
    dataExposed: ["input", "position", "yaw", "ground state"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:three-scene-renderer",
    purpose: "Compose GoldRush Three.js sites from descriptors while keeping presentation separate from state.",
    publicApi: ["mount", "render", "unmount", "snapshot"],
    internalApi: ["mountSiteRenderer", "syncSceneDescriptors", "disposeSiteResources"],
    events: ["goldrush.rendererMounted", "goldrush.renderFrame"],
    snapshot: ["screen", "site", "objectCount", "loadedKitGroups"],
    dataExposed: ["site id", "renderer state", "object count", "kit groups"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:gold-field-renderer",
    purpose: "Render GoldRush terrain bands, canyon basin, trails, gold zones, and readable landmarks.",
    publicApi: ["build", "snapshot", "validate"],
    internalApi: ["createBandedTriangleTerrainGeometry", "mountCanyonCompositionKit", "mountRouteKit"],
    events: ["goldrush.goldFieldBuilt"],
    snapshot: ["terrainBands", "canyonComposition", "routeMarkers", "goldNodes"],
    dataExposed: ["terrain mesh", "routes", "landmarks", "gold markers"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:desert-prop-kits",
    purpose: "Turn GoldRush micro object descriptors into readable instanced desert props.",
    publicApi: ["batch", "snapshot", "validate"],
    internalApi: ["groupMicroKits", "resolvePropMaterial", "placeByEnvironmentSpace"],
    events: ["goldrush.microPropsBatched"],
    snapshot: ["microKitCount", "families", "clusters"],
    dataExposed: ["micro kit id", "family", "role", "placement"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:lobby-character-preview",
    purpose: "Render and rotate the GoldRush lobby prospector character on a pedestal.",
    publicApi: ["mount", "rotate", "snapshot"],
    internalApi: ["buildProceduralRig", "bindPointerDrag", "syncPartySlots"],
    events: ["goldrush.characterPreviewRotated"],
    snapshot: ["rotation", "pose", "partySlotFocus"],
    dataExposed: ["rotation", "pose", "character source"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:music-and-stingers",
    purpose: "Select GoldRush music, cashout, ambush, loading, and result cue slots.",
    publicApi: ["snapshot", "validate"],
    internalApi: ["resolvePhaseCue", "dedupeOneShots", "avoidHummingFallbacks"],
    events: ["goldrush.audioCueChanged", "goldrush.audioOneShot"],
    snapshot: ["musicCueId", "oneShots", "crossfadeSeconds"],
    dataExposed: ["cue id", "phase", "crossfade", "one-shot list"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:prospector-animation",
    purpose: "Expose GoldRush prospector idle, run, aim, mine, carry, cashout, and damage animation state.",
    publicApi: ["snapshot", "validate"],
    internalApi: ["resolveLegacyAnimatorParams", "mapCargoToPose", "mapCombatToPose"],
    events: ["goldrush.animationChanged"],
    snapshot: ["clipSlotIds", "params", "actionState"],
    dataExposed: ["clip slots", "anim params", "action state"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:mine-hold-action",
    purpose: "Turn hold interaction progress into GoldRush gold mining payouts, claim pressure, and mining receipts.",
    publicApi: ["holdMine", "snapshot", "validate"],
    internalApi: ["nearestMiningSite", "applyPayout", "markSiteDepleted", "buildClaimPressure", "recordMiningReceipt"],
    events: ["goldrush.goldMined", "goldrush.miningCancelled", "goldrush.miningReceiptRecorded"],
    snapshot: ["activeSiteId", "progress", "sitesTouched", "readability", "receipts"],
    dataExposed: ["site id", "progress", "payout", "depleted", "claim heat", "noise radius", "reward preview", "receipt"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:gold-carrying",
    purpose: "Own GoldRush carried gold, capacity, drops, and cargo pressure.",
    publicApi: ["seed", "add", "drop", "snapshot"],
    internalApi: ["clampGold", "calculateWeightPenalty", "clearOnCashout"],
    events: ["goldrush.cargoAdded", "goldrush.cargoDropped"],
    snapshot: ["carriedByPlayer", "capacity", "weightPenalty"],
    dataExposed: ["player id", "carried gold", "weight penalty"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:cashout-sites",
    purpose: "Own GoldRush cashout zones, contested extraction pressure, deposits, and scene handoffs.",
    publicApi: ["holdExtraction", "completeExtraction", "deposit", "snapshot"],
    internalApi: ["nearestExtractionSite", "updateExtractionSiteContest", "recordExtractionReceipt", "advanceCashoutScene"],
    events: ["goldrush.extractionStarted", "goldrush.extractionContested", "goldrush.extracted"],
    snapshot: ["sites", "progress", "contestState", "receipt", "bankedGold"],
    dataExposed: ["site id", "progress", "contest status", "receipt id", "banked gold"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:ambush-pressure",
    purpose: "Increase GoldRush combat pressure while exposing readable threat telegraphs, lanes, counterplay, and combat receipts.",
    publicApi: ["enter", "damage", "fire", "snapshot"],
    internalApi: ["activateThreats", "createCombatReadability", "recordCombatReceipt"],
    events: ["goldrush.ambushStarted", "goldrush.damageApplied", "goldrush.shotFired", "goldrush.threatTelegraphed"],
    snapshot: ["active", "pressure", "readability", "receipts", "threats"],
    dataExposed: ["pressure", "telegraph id", "danger lane", "damage", "counterplay tags"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-action-surface",
    purpose: "Compose mining, cashout, cover, cargo, and risk facts into one player-facing action prompt surface.",
    publicApi: ["update", "snapshot", "validate"],
    internalApi: ["choosePrimaryAction", "resolveHoldProgress", "rankAvailableActions"],
    events: ["goldrush.playerActionSurfaceChanged"],
    snapshot: ["primaryAction", "availableActions", "cargo", "risk"],
    dataExposed: ["action id", "prompt", "input", "hold ratio", "target id", "risk state"],
    validator: "tools/validation/validate-player-action-surface.mjs",
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-driven-extraction-route",
    purpose: "Track whether mine, carry, cashout, receipt, and results stages are truly player-driven and domain-owned.",
    publicApi: ["update", "snapshot", "validate"],
    internalApi: ["resolveStageStatus", "countHelperDebt", "rankNextPlayableGap"],
    events: ["goldrush.playerDrivenRouteChanged"],
    snapshot: ["stageOrder", "stages", "resolvedStages", "playerDrivenStages", "helperDebt"],
    dataExposed: ["stage id", "status", "domain path", "evidence", "gaps", "helper debt"],
    validator: "tools/validation/validate-player-driven-extraction-route.mjs",
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-route-guidance",
    purpose: "Expose walkable route targets and camera-relative input hints for mine, carry, and cashout traversal.",
    publicApi: ["update", "snapshot", "validate"],
    internalApi: ["resolveMineTarget", "resolveCashoutTarget", "createCameraRelativeInputHint"],
    events: ["goldrush.playerRouteGuidanceChanged"],
    snapshot: ["currentLegId", "target", "cameraRelativeInput", "legs", "routeStatus"],
    dataExposed: ["target id", "target position", "distance", "keys", "look delta", "leg status"],
    validator: "tools/validation/validate-player-route-guidance.mjs",
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-guidance-cue",
    purpose: "Convert route guidance and action-surface state into one diegetic player-facing world cue.",
    publicApi: ["update", "snapshot", "validate"],
    internalApi: ["resolveCueRole", "resolveDistanceBand", "resolveCueWorldPosition"],
    events: ["goldrush.playerGuidanceCueChanged"],
    snapshot: ["visible", "target", "cue", "action", "readability"],
    dataExposed: ["target kind", "distance band", "cue role", "shape", "input", "readability policy"],
    validator: "tools/validation/validate-player-guidance-cue.mjs",
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:player-loop-readiness",
    purpose: "Expose a human-view loop matrix proving cue, hold, cargo, cashout, receipt, and results readiness.",
    publicApi: ["update", "snapshot", "validate"],
    internalApi: ["composeRouteState", "composeRendererEvidence", "countHelperDebt", "rankLoopGap"],
    events: ["goldrush.playerLoopReadinessChanged"],
    snapshot: ["stageOrder", "stages", "resolvedStages", "blockedStages", "proofPolicy", "helperDebt"],
    dataExposed: ["stage id", "status", "domain path", "evidence", "gap", "proof policy", "helper debt"],
    validator: "tools/validation/validate-player-loop-readiness.mjs",
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:match-loop",
    purpose: "Own the linear GoldRush phase order from lobby through results.",
    publicApi: ["start", "advancePhase", "tick", "requestEnd", "snapshot"],
    internalApi: ["preventPhaseRegression", "recordPhaseHistory", "resolveFinalRush"],
    events: ["goldrush.matchStarted", "goldrush.phaseChanged", "goldrush.matchEnding"],
    snapshot: ["phase", "tick", "elapsedSeconds", "status"],
    dataExposed: ["phase", "clock", "status", "history"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:extraction-receipts",
    purpose: "Record accepted, rejected, and duplicate GoldRush extraction and handoff receipts.",
    publicApi: ["recordExtraction", "recordHandoff", "receipt", "snapshot"],
    internalApi: ["dedupeReceipt", "applyFinalRushMultiplier", "indexReceipts"],
    events: ["goldrush.receiptAccepted", "goldrush.receiptRejected"],
    snapshot: ["receipts", "appliedIds", "rejectedIds", "totals"],
    dataExposed: ["receipt id", "player id", "team id", "score value", "frontier condition"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:gold-rush-scoring",
    purpose: "Apply GoldRush extraction, combat, survival, and final-rush scoring rules.",
    publicApi: ["applyExtractionReceipt", "applyCombatResult", "applySurvivalBonus", "snapshot"],
    internalApi: ["scoreTeam", "sortLeaders", "applyPressureMultiplier"],
    events: ["goldrush.scoreApplied", "goldrush.leaderChanged"],
    snapshot: ["players", "teams", "leaders", "modifiers"],
    dataExposed: ["player score", "team score", "leader", "modifier"],
  }),
  createGoldRushContract({
    domainPath: "n:goldrush:results-screen",
    purpose: "Finalize and expose the GoldRush winner, placements, awards, combat outcome, and result summary.",
    publicApi: ["finalize", "snapshot", "validate"],
    internalApi: ["rankTeams", "resolveAwards", "summarizeCombatOutcome", "freezeResultState"],
    events: ["goldrush.resultsFinalized"],
    snapshot: ["winner", "placements", "awards", "finalReason", "frontierConditionSummary", "extractionContestSummary", "combatOutcomeSummary"],
    dataExposed: ["winner", "placement", "award", "reason", "condition summary", "contest summary", "combat summary"],
  }),
]);

export const goldRushKitPairings = Object.freeze([
  ["n:runtime:domain-registry", "n:goldrush:runtime"],
  ["n:runtime:events", "n:goldrush:replay-summary"],
  ["n:runtime:snapshot", "n:goldrush:match-snapshot"],
  ["n:runtime:validation", "n:goldrush:reality-status"],
  ["n:scene:site-loader", "n:goldrush:scene-flow"],
  ["n:scene:transition", "n:goldrush:train-loading"],
  ["n:network:party-room", "n:goldrush:party-lobby"],
  ["n:network:room-partitions", "n:goldrush:room-orchestration"],
  ["n:world:terrain-heightfield", "n:goldrush:desert-terrain"],
  ["n:world:terrain-raycast", "n:goldrush:player-grounding"],
  ["n:world:terrain-patches", "n:goldrush:terrain-patch-windows"],
  ["n:world:placement-raycast", "n:goldrush:prop-placement"],
  ["n:physics:world", "n:goldrush:terrain-physics"],
  ["n:physics:collider", "n:goldrush:mountain-blockers"],
  ["n:physics:query", "n:goldrush:ground-probes"],
  ["n:control:third-person-camera", "n:goldrush:exploration-camera"],
  ["n:control:character-movement", "n:goldrush:prospector-movement"],
  ["n:render:three-scene", "n:goldrush:three-scene-renderer"],
  ["n:render:terrain-bands", "n:goldrush:gold-field-renderer"],
  ["n:render:micro-object-instancing", "n:goldrush:desert-prop-kits"],
  ["n:render:character-preview", "n:goldrush:lobby-character-preview"],
  ["n:audio:cue-state", "n:goldrush:music-and-stingers"],
  ["n:animation:state", "n:goldrush:prospector-animation"],
  ["n:gameplay:interaction-hold", "n:goldrush:mine-hold-action"],
  ["n:gameplay:cargo", "n:goldrush:gold-carrying"],
  ["n:gameplay:extraction", "n:goldrush:cashout-sites"],
  ["n:gameplay:combat-pressure", "n:goldrush:ambush-pressure"],
  ["n:match:lifecycle", "n:goldrush:match-loop"],
  ["n:match:receipts", "n:goldrush:extraction-receipts"],
  ["n:match:scoring", "n:goldrush:gold-rush-scoring"],
  ["n:match:results", "n:goldrush:results-screen"],
].map(([genericDomainPath, goldRushDomainPath]) => Object.freeze({ genericDomainPath, goldRushDomainPath })));

export function createDomainKitContractSnapshot({ engine = null } = {}) {
  const installed = Object.entries(engine?.domainServiceKits ?? {}).map(([id, metadata]) => ({
    id,
    apiName: metadata.apiName,
    domain: metadata.domain,
    domainPath: metadata.domainPath ?? `n:${metadata.domain}`,
    layer: metadata.layer ?? "runtime-installed",
    stability: metadata.stability,
    version: metadata.version,
  }));

  return structuredClone({
    version: KIT_CONTRACT_VERSION,
    templateFields: KIT_CONTRACT_FIELDS,
    generic: {
      count: genericIncubatorKitContracts.length,
      contracts: genericIncubatorKitContracts,
    },
    goldRush: {
      count: goldRushKitContracts.length,
      contracts: goldRushKitContracts,
    },
    pairings: goldRushKitPairings,
    installed,
  });
}

export function validateDomainKitContractCatalog({
  generic = genericIncubatorKitContracts,
  goldRush = goldRushKitContracts,
  pairings = goldRushKitPairings,
  docs = null,
} = {}) {
  const failures = [];
  const genericDomainPaths = new Set();
  const goldRushDomainPaths = new Set();

  for (const contract of generic) {
    validateContract(contract, failures, { layer: "generic-incubator" });
    if (genericDomainPaths.has(contract.domainPath)) failures.push(`duplicate-generic-domain-path:${contract.domainPath}`);
    genericDomainPaths.add(contract.domainPath);
    const genericText = JSON.stringify({
      purpose: contract.purpose,
      publicApi: contract.publicApi,
      internalApi: contract.internalApi,
      events: contract.events,
      snapshot: contract.snapshot,
      dataExposed: contract.dataExposed,
      graduationRule: contract.graduationRule,
    }).toLowerCase();
    if (genericText.includes("goldrush") || genericText.includes("gold rush")) {
      failures.push(`generic-contract-contains-game-name:${contract.domainPath}`);
    }
  }

  for (const contract of goldRush) {
    validateContract(contract, failures, { layer: "goldrush-custom" });
    if (!contract.domainPath.startsWith("n:goldrush:")) failures.push(`goldrush-contract-wrong-domain:${contract.domainPath}`);
    if (goldRushDomainPaths.has(contract.domainPath)) failures.push(`duplicate-goldrush-domain-path:${contract.domainPath}`);
    goldRushDomainPaths.add(contract.domainPath);
  }

  for (const pairing of pairings) {
    if (!genericDomainPaths.has(pairing.genericDomainPath)) failures.push(`pairing-missing-generic:${pairing.genericDomainPath}`);
    if (!goldRushDomainPaths.has(pairing.goldRushDomainPath)) failures.push(`pairing-missing-goldrush:${pairing.goldRushDomainPath}`);
  }

  if (docs) {
    for (const contract of [...generic, ...goldRush]) {
      if (!docs.includes(contract.domainPath)) failures.push(`docs-missing-domain-path:${contract.domainPath}`);
    }
  }

  return {
    passed: failures.length === 0,
    failures,
    counts: {
      generic: generic.length,
      goldRush: goldRush.length,
      pairings: pairings.length,
    },
  };
}

export function domainPathToServiceDomain(domainPath) {
  return domainPath.replace(/^n:/, "").replaceAll(":", "-");
}

function validateContract(contract, failures, { layer }) {
  if (contract.layer !== layer) failures.push(`wrong-layer:${contract.domainPath ?? "unknown"}`);
  for (const field of KIT_CONTRACT_FIELDS) {
    if (!Object.prototype.hasOwnProperty.call(contract, field)) failures.push(`missing-${field}:${contract.domainPath ?? "unknown"}`);
  }
  if (!/^n:[a-z][a-z0-9-]*(?::[a-z][a-z0-9-]*)+$/.test(contract.domainPath ?? "")) {
    failures.push(`invalid-domain-path:${contract.domainPath ?? "unknown"}`);
  }
  for (const field of ["publicApi", "internalApi", "events", "snapshot", "dataExposed"]) {
    if (!Array.isArray(contract[field]) || contract[field].length === 0) failures.push(`empty-${field}:${contract.domainPath}`);
  }
  for (const field of ["purpose", "reset", "validator", "graduationRule"]) {
    if (typeof contract[field] !== "string" || contract[field].trim().length === 0) failures.push(`empty-${field}:${contract.domainPath}`);
  }
}
